quarkus.application.name=customer-intent-backend
quarkus.http.port=8080

model.service.url=http://customer-intent-inference.customer-intent-demo.svc.cluster.local:8080
model.service.timeout=5s
routing.default-threshold=0.80

quarkus.micrometer.export.prometheus.path=/metrics
quarkus.smallrye-health.root-path=/health

quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
