apiVersion: v1
kind: Namespace
metadata:
  name: fine-tuning
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    openshift.io/display-name: "Fine Tuning"
    openshift.io/description: "Data science project for fine-tuning ML models"
