quarkus.rest-client.model-service.url=${MODEL_SERVICE_URL:http://customer-intent-inference.customer-intent-demo.svc.cluster.local:8080}
quarkus.rest-client.model-service.connect-timeout=5000
quarkus.rest-client.model-service.read-timeout=5000
