apiVersion: v1
kind: Secret
metadata:
  name: minio-s3-connection
  namespace: fine-tuning
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    openshift.io/description: "MinIO S3 connection for OpenShift AI"
    openshift.io/display-name: "MinIO S3"
    opendatahub.io/connection-type: s3
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: admin
  AWS_SECRET_ACCESS_KEY: "12345678"
  AWS_DEFAULT_REGION: us-east-1
  AWS_S3_ENDPOINT: http://minio-api.minio.svc.cluster.local:9000
  AWS_S3_BUCKET: fine-tuning
