FROM registry.access.redhat.com/ubi9/nginx-124:latest

USER root
COPY nginx.conf /etc/nginx/nginx.conf
COPY src/index.web.html /usr/share/nginx/html/index.html
COPY src/styles.css /usr/share/nginx/html/styles.css
COPY src/renderer-web.js /usr/share/nginx/html/renderer-web.js

RUN mkdir -p /var/log/nginx /var/cache/nginx && \
    chown -R 1001:0 /var/log/nginx /var/cache/nginx /usr/share/nginx/html /etc/nginx/nginx.conf && \
    chmod -R g+rwX /var/log/nginx /var/cache/nginx

USER 1001
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
