apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: banking77-training
  namespace: customer-intent-demo
  labels:
    opendatahub.io/dashboard: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
