apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-intent-model
  namespace: customer-intent-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
