apiVersion: v1
kind: Service
metadata:
  name: customer-intent-inference
  namespace: customer-intent-demo
  labels:
    app: customer-intent-inference
spec:
  selector:
    app: customer-intent-inference
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: customer-intent-inference
  namespace: customer-intent-demo
spec:
  to:
    kind: Service
    name: customer-intent-inference
  port:
    targetPort: http
  tls:
    termination: edge
