apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-intent-pipeline
  namespace: customer-intent-demo
  labels:
    opendatahub.io/dashboard: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: customer-intent-pipeline-edit
  namespace: customer-intent-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: customer-intent-pipeline
    namespace: customer-intent-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: customer-intent-pipeline-mlflow
  namespace: customer-intent-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: customer-intent-pipeline
    namespace: customer-intent-demo
